version: "3"

services:
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pgpassword

    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - compose-network

  app:
    depends_on:
      - db
    build: .
    command: yarn start
    ports:
      - 3333:3333
    volumes:
      - .:/app
    networks:
      - compose-network
      

networks: 
  compose-network: