version: "3"

services:
  
  db:
    container_name: db
    image: "postgres" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    
    volumes:
    - postgres_data:/var/lib/postgresql/data 
    networks:
      - network-api 
    
  api:
    container_name: api
    depends_on:
      - db
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - network-api

volumes: 
  postgres_data:
  node_modules:


networks:
  network-api:
    external:
      name: network-api

