version: "3"

services:
  app:
    build: .
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - postgres-compose-network
      

  teste-postgres-compose:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: "ziguen"
    ports:
      - "2222:2222"
    volumes:
      - /home/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      

networks: 
  postgres-compose-network:
    driver: bridge