version: "3"

services:
  app:
    build: .
    command: yarn start
    ports:
      - 3333:3333
    volumes:
      - .:/app
    networks:
      - compose-network
      

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/Docker-Compose
    networks:
      - compose-network
      

networks: 
  compose-network:
    driver: bridge