version: "3"

services:
  
  db:
    container_name: db
    image: "postgres" 
    env_file:
      - database.env 
    
    volumes:
    - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - network-api 
    
  app:
    container_name: app
    depends_on:
      - db
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - network-api

volumes: 
  postgres_data:
  node_modules:

networks:
  network-api: