version: "3"

services:
  
  db:
    image: "postgres" 
    env_file:
      - database.env 
    ports:
      - 5432:5432
    volumes:
      - ./dados:/var/lib/postgresql/data
    networks:
      - compose-network
      
    
  app:
    depends_on:
      - db
    build: .
    command: yarn start
    ports:
      - 3333:3333
    volumes:
      - .:/app
    networks:
      - compose-network

networks:
  compose-network:
    external:
      name: compose-network


